version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    container_name: my_app
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/mydatabase?authSource=admin
      SECRET_KEY: your-secret-key
      PASSWORD: your-standard-password
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  mongodb-data:
